ALTER TABLE todos
ADD COLUMN user_id INTEGER REFERENCES users(id) ON DELETE CASCADE;

UPDATE todos SET user_id = (SELECT id FROM users LIMIT 1) WHERE user_id IS NULL;

ALTER TABLE todos ALTER COLUMN user_id SET NOT NULL; 