openapi: 3.0.3
info:
  title: ToDo App API
  description: API for managing todos with JWT authentication
  version: 1.0.0

servers:
  - url: http://localhost:3000/
    description: Local development server

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Todo:
      type: object
      properties:
        id:
          type: string
        text:
          type: string
        done:
          type: boolean
      required:
        - title

    UserCredentials:
      type: object
      properties:
        email:
          type: string
          format: email
        username:
          type: string
        name:
          type: string
        password:
          type: string
      required:
        - email
        - password
    LoginCredentials:
      type: object
      properties:
        usernameOrEmail:
          type: string
        password:
          type: string
      required:
        - usernameOrEmail
        - password


paths:
  /auth/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCredentials'
      responses:
        '201':
          description: User registered successfully
        '400':
          description: Invalid input

  /auth/login:
    post:
      summary: Log in and receive a JWT
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginCredentials'
      responses:
        '200':
          description: Authentication successful, returns JWT
        '401':
          description: Invalid credentials

  /api/todos:
    get:
      summary: Get all todos for the authenticated user
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of todos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Todo'
        '401':
          description: Unauthorized

    post:
      summary: Add a new todo
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Todo'
      responses:
        '201':
          description: Todo created
        '400':
          description: Invalid input
        '401':
          description: Unauthorized

  /api/todos/{id}:
    delete:
      summary: Delete a todo by ID
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Todo deleted
        '404':
          description: Todo not found
        '401':
          description: Unauthorized
